name: http_and_dio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0-134.5.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  http: ^0.13.4
  dio: ^4.0.4
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

